# Generated by Django 4.0.3 on 2022-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_browsergame_users_viewed'),
        ('users', '0002_pais_user_estado_user_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_viewed',
            field=models.ManyToManyField(to='games.browsergame', verbose_name='Games Visualizados'),
        ),
    ]
