# Generated by Django 4.0.3 on 2022-03-24 04:35

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='BrowserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('game_url', models.URLField(verbose_name='Url do Jogo')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Url do Vídeo')),
                ('descricao', models.TextField(max_length=255)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='games/uploads/imgs', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='games.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação')),
                ('comentario', models.TextField(blank=True, max_length=255, null=True, verbose_name='Comentário')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.browsergame', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
