# Generated by Django 4.0.3 on 2022-03-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browsergame',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='browsergame',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
    ]
