# Generated by Django 4.0.3 on 2022-05-04 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_browsergame_users_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Users Liked'),
        ),
    ]
