# Generated by Django 4.0.3 on 2022-05-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_avaliacao_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsergame',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
