# Generated by Django 4.0.3 on 2022-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_browsergame_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
