# Generated by Django 4.0.3 on 2022-05-14 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_alter_avaliacao_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsergame',
            name='users_viewed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users Viewed'),
        ),
    ]
