# Generated by Django 4.0.3 on 2022-05-14 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_alter_browsergame_users_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Users Liked'),
        ),
    ]
